version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: tigu_mysql
    command: ["mysqld", "--mysql-native-password=ON", "--lower_case_table_names=1"]
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tigu_b2b
      MYSQL_USER: tigu_user
      MYSQL_PASSWORD: tigu_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7
    container_name: tigu_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bff:
    build:
      context: ./bff
    container_name: tigu_bff
    env_file:
      - bff/.env.example
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: [
      "uvicorn",
      "app.main:app",
      "--reload",
      "--host",
      "0.0.0.0",
      "--port",
      "8000"
    ]
    ports:
      - "8000:8000"
    volumes:
      - ./bff/app:/code/app

  frontend:
    build:
      context: ./frontend
    container_name: tigu_frontend
    environment:
      VITE_API_URL: http://localhost:8000/api
      VITE_GOOGLE_MAPS_KEY: demo-key
    depends_on:
      - bff
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  mysql_data:
  frontend_node_modules:
